### ISSUE TITLE
Post grid links double underline

### ISSUE THREAD

**Issue by quicoto** [studiopress/atomic-blocks#81] opened 2019-03-22 07:58 UTC
Hello,

I just upgraded to Version 1.5.5 of the plugin and now I see double underline for the Post Grid links.

There's the text-decoration and the box-shadow 

WordPress 5.1.1
Theme Atomic BlocksVersion: 1.2.3

https://www.ricardtorres.com/archive/
![Double Underline](https://cldup.com/rOg6e2HDT8.png)

https://www.ricardtorres.com/
![Double Underline](https://cldup.com/kwC3K1LF9O.png)

Thank you in advance.

**Comment by mindctrl** [comment] 2019-03-22 22:33
@quicoto thanks for the report! We'll fix this in the next update.

**Comment by mindctrl** [comment] 2019-04-08 13:28
I'm not seeing this now. @mikemcalister can you reproduce this?

**Comment by quicoto** [comment] 2019-04-08 13:54
@mindctrl it comes from here 

![DevTools](https://cloudup.com/cl_bKN2s02O+)

**Comment by mindctrl** [comment] 2019-04-08 19:00
@quicoto do you see this on the latest versions of both the theme and plugin? I just set up a new site with Atomic Blocks (plugin) 1.6.0 and Atomic Blocks (theme) 1.2.3 and it doesn't do this.

**Comment by quicoto** [comment] 2019-04-08 19:29
@mindctrl ok I've found the issue, I did set a custom "Accent Color" from the Customizer

Still, I think it's a defect. Not sure how the Customizer works but we should have box shadow and border at the same time. It is possible to unify the CSS property to the Customizer overwrites the theme's default?

![Customier](https://cldup.com/2UY6MxJzLO.png)

**Comment by mindctrl** [comment] 2019-04-08 20:56
Now I can reproduce. Good find! I think this should be addressed in the theme since it's adding the box shadow. I'll close this issue and open one in the theme repo. Thanks for the detailed report!

**Closed by mindctrl** 2019-04-08 20:56 UTC
Labels: bug
